# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Monument
tagline:          'for the digital age'
description:      "A monument is a celebration of someone's impact on the world, and an acknowledgement of the empty void they leave behind them."
url:              http://monument.monks.co
baseurl:          /

author:
  name:           'Andrew Monks'
  url:            https://monks.co
